import { Dimensions, StyleSheet } from "react-native";
import { shared } from "./shared";

const { width: SCREEN_WIDTH } = Dimensions.get("window");

export const styles = StyleSheet.create({
	...shared,

	// Header
	header: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		paddingHorizontal: 16,
		paddingVertical: 12,
		borderBottomWidth: 1,
	},
	headerTitle: { fontSize: 26, fontWeight: "800" },
	postBtn: {
		flexDirection: "row",
		alignItems: "center",
		gap: 5,
		paddingHorizontal: 14,
		paddingVertical: 8,
		borderRadius: 20,
	},
	postBtnText: { fontSize: 14, fontWeight: "600" },
	mapBtn: {
		width: 38,
		height: 38,
		borderRadius: 19,
		alignItems: "center",
		justifyContent: "center",
	},

	// Filter Bar
	filterBarWrapper: { height: 50, justifyContent: "center", overflow: "hidden" },
	filterBar: { flexDirection: "row", paddingHorizontal: 12, gap: 8, alignItems: "center", height: 50 },
	filterChip: {
		flexDirection: "row",
		alignItems: "center",
		gap: 4,
		paddingHorizontal: 10,
		height: 30,
		borderRadius: 15,
		borderWidth: 1.5,
	},
	filterChipText: { fontSize: 13, fontWeight: "600", includeFontPadding: false },

	// Feed list / empty
	feedList: { padding: 12, paddingBottom: 32 },
	loadingWrap: { flex: 1, justifyContent: "center", alignItems: "center" },
	emptyWrap: {
		flexGrow: 1,
		justifyContent: "center",
		alignItems: "center",
		padding: 32,
		gap: 12,
	},
	emptyIcon: { fontSize: 56, marginBottom: 4 },
	emptyTitle: { fontSize: 20, fontWeight: "700", textAlign: "center" },
	emptySubtitle: { fontSize: 14, textAlign: "center", lineHeight: 20, maxWidth: 260 },
	emptyBtn: { marginTop: 8, paddingHorizontal: 24, paddingVertical: 14, borderRadius: 24 },
	emptyBtnText: { fontSize: 15, fontWeight: "700" },

	// Post Card
	card: {
		borderRadius: 20,
		overflow: "hidden",
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.07,
		shadowRadius: 8,
		elevation: 2,
	},
	cardHeader: { flexDirection: "row", alignItems: "center", padding: 12, gap: 10 },
	avatarCircle: {
		width: 40,
		height: 40,
		borderRadius: 20,
		justifyContent: "center",
		alignItems: "center",
		overflow: "hidden",
	},
	avatarImg: { width: 40, height: 40 },
	avatarInitial: { fontSize: 18, fontWeight: "700" },
	headerMeta: { flex: 1 },
	headerNameRow: { flexDirection: "row", alignItems: "center", gap: 6 },
	authorName: { fontSize: 14, fontWeight: "700" },
	proBadge: { paddingHorizontal: 6, paddingVertical: 2, borderRadius: 8 },
	proBadgeText: { fontSize: 10, fontWeight: "600", color: "#C9A84C" },
	postTime: { fontSize: 12, marginTop: 2 },
	typeBadge: {
		flexDirection: "row",
		alignItems: "center",
		alignSelf: "flex-start",
		gap: 4,
		paddingHorizontal: 8,
		paddingVertical: 4,
		borderRadius: 10,
	},
	typeBadgeIcon: { fontSize: 12 },
	typeBadgeLabel: { fontSize: 11, fontWeight: "700" },

	postImage: { width: "100%", height: SCREEN_WIDTH * 0.75 },

	eventDetails: { paddingHorizontal: 14, paddingTop: 12, paddingBottom: 4, borderTopWidth: 1 },
	eventTitle: { fontSize: 16, fontWeight: "700", marginBottom: 6 },
	eventMeta: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
	eventMetaText: { fontSize: 13 },

	carDetails: { paddingHorizontal: 14, paddingTop: 12, paddingBottom: 4 },
	carLabel: { fontSize: 16, fontWeight: "700" },
	carLocation: { fontSize: 12, marginTop: 2 },

	actions: { flexDirection: "row", paddingHorizontal: 12, paddingTop: 10, paddingBottom: 4, gap: 16 },
	actionBtn: { flexDirection: "row", alignItems: "center", gap: 5 },
	likeIcon: { fontSize: 20 },
	commentIcon: { fontSize: 20 },
	actionCount: { fontSize: 14 },

	captionWrap: {
		flexDirection: "row",
		flexWrap: "wrap",
		paddingHorizontal: 14,
		paddingBottom: 14,
		paddingTop: 4,
	},
	captionAuthor: { fontSize: 13, fontWeight: "700" },
	captionText: { fontSize: 13, lineHeight: 18 },

	// Create Post Modal
	modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.55)", justifyContent: "flex-end" },
	modalSheet: { borderTopLeftRadius: 28, borderTopRightRadius: 28, maxHeight: "92%" },
	modalHeader: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		paddingHorizontal: 20,
		paddingTop: 20,
		paddingBottom: 12,
	},
	modalTitle: { fontSize: 18, fontWeight: "700" },
	modalHeaderAction: { fontSize: 15, fontWeight: "500", minWidth: 52 },

	typeStep: { paddingHorizontal: 20, paddingBottom: 36, gap: 12 },
	typeStepLabel: { fontSize: 14, fontWeight: "600", marginBottom: 4 },
	typeOption: {
		flexDirection: "row",
		alignItems: "center",
		padding: 16,
		borderRadius: 18,
		borderWidth: 2,
		gap: 14,
	},
	typeOptionIcon: { fontSize: 28 },
	typeOptionLabel: { fontSize: 16, fontWeight: "700", marginBottom: 3 },
	typeOptionDesc: { fontSize: 13, lineHeight: 17 },
	typeCheckmark: {
		width: 26,
		height: 26,
		borderRadius: 13,
		justifyContent: "center",
		alignItems: "center",
	},
	continueBtn: { paddingVertical: 16, borderRadius: 18, alignItems: "center", marginTop: 8 },
	continueBtnText: { fontSize: 16, fontWeight: "700" },

	detailsStep: { paddingHorizontal: 20, paddingBottom: 36, gap: 12 },
	selectedTypePill: {
		flexDirection: "row",
		alignItems: "center",
		gap: 6,
		alignSelf: "flex-start",
		paddingHorizontal: 12,
		paddingVertical: 6,
		borderRadius: 12,
		marginBottom: 4,
	},
	selectedTypePillIcon: { fontSize: 16 },
	selectedTypePillLabel: { fontSize: 13, fontWeight: "700" },

	photoPicker: {
		height: 170,
		borderRadius: 16,
		borderWidth: 1.5,
		borderStyle: "dashed",
		overflow: "hidden",
		justifyContent: "center",
		alignItems: "center",
	},
	photoPickerEmpty: { alignItems: "center", gap: 8 },
	photoPickerLabel: { fontSize: 14, fontWeight: "500" },
	photoPickerPreview: { width: "100%", height: "100%" },

	fieldGroup: { gap: 10 },
	input: { borderRadius: 14, paddingHorizontal: 14, paddingVertical: 13, fontSize: 15 },
	captionInput: { minHeight: 90, paddingTop: 13 },

	locationRow: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: 8 },
	locationInput: { flex: 1, height: 44, borderRadius: 10, paddingHorizontal: 14, fontSize: 15 },
	locationBtn: { height: 44, paddingHorizontal: 12, borderRadius: 10, justifyContent: "center", alignItems: "center" },
	locationBtnText: { fontSize: 13, fontWeight: "600" },

	// User Profile Sheet
	profileModalOverlay: { flex: 1, justifyContent: "flex-end" },
	profileModalBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(0,0,0,0.5)" },
	profileSheet: { borderTopLeftRadius: 28, borderTopRightRadius: 28, maxHeight: "88%" },
	sheetHandle: { alignItems: "center", paddingTop: 12, paddingBottom: 4 },
	handleBar: { width: 36, height: 4, borderRadius: 2 },
	closeBtn: { alignSelf: "flex-end", paddingHorizontal: 16, paddingVertical: 6 },

	profileAvatarSection: { alignItems: "center", paddingTop: 8, paddingBottom: 20, gap: 10 },
	profileAvatar: {
		width: 80,
		height: 80,
		borderRadius: 40,
		justifyContent: "center",
		alignItems: "center",
		overflow: "hidden",
	},
	profileAvatarImg: { width: 80, height: 80 },
	profileAvatarInitial: { fontSize: 32, fontWeight: "700" },
	profileName: { fontSize: 20, fontWeight: "700" },
	profilePhotoBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 10 },
	profilePhotoBadgeText: { fontSize: 13, fontWeight: "600" },

	profileStats: {
		flexDirection: "row",
		alignItems: "center",
		marginHorizontal: 16,
		borderRadius: 18,
		padding: 16,
	},
	profileStatItem: { flex: 1, alignItems: "center" },
	profileStatValue: { fontSize: 22, fontWeight: "700" },
	profileStatLabel: { fontSize: 12, marginTop: 2 },
	profileStatDivider: { width: 1, height: 32 },

	followBtn: { marginHorizontal: 16, marginTop: 14, paddingVertical: 14, borderRadius: 14, alignItems: "center" },
	followBtnText: { fontSize: 15, fontWeight: "700" },

	profileGridTitle: {
		fontSize: 11,
		fontWeight: "700",
		letterSpacing: 1.2,
		paddingHorizontal: 16,
		marginTop: 20,
		marginBottom: 10,
	},
	profileNoPosts: { textAlign: "center", paddingVertical: 24, fontSize: 14 },
	postsGrid: { flexDirection: "row", flexWrap: "wrap", paddingHorizontal: 12, gap: 3 },
	gridCell: {
		width: (SCREEN_WIDTH - 24 - 6) / 3,
		height: (SCREEN_WIDTH - 24 - 6) / 3,
		borderRadius: 8,
		overflow: "hidden",
	},
	gridImage: { width: "100%", height: "100%" },
	gridImagePlaceholder: { width: "100%", height: "100%", justifyContent: "center", alignItems: "center" },
	gridPlaceholderIcon: { fontSize: 28 },

	// Comments Sheet
	commentsSheet: { borderTopLeftRadius: 28, borderTopRightRadius: 28, maxHeight: "88%", flex: 1 },
	commentsHeader: {
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "space-between",
		paddingHorizontal: 20,
		paddingVertical: 14,
		borderBottomWidth: 1,
	},
	commentsTitle: { fontSize: 17, fontWeight: "700" },
	commentsEmpty: { flex: 1, alignItems: "center", justifyContent: "center", paddingVertical: 48, gap: 10 },
	commentsEmptyIcon: { fontSize: 40 },
	commentsEmptyText: { fontSize: 14 },
	commentsList: { padding: 16, gap: 14 },
	commentRow: { flexDirection: "row", gap: 10, alignItems: "flex-start" },
	commentAvatar: {
		width: 34,
		height: 34,
		borderRadius: 17,
		justifyContent: "center",
		alignItems: "center",
		overflow: "hidden",
	},
	commentAvatarImg: { width: 34, height: 34 },
	commentAvatarInitial: { fontSize: 14, fontWeight: "700" },
	commentBubble: { flex: 1, borderRadius: 16, paddingHorizontal: 12, paddingVertical: 10 },
	commentBubbleHeader: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 4 },
	commentAuthor: { fontSize: 13, fontWeight: "700" },
	commentTime: { fontSize: 11 },
	commentText: { fontSize: 14, lineHeight: 19 },
	commentInputRow: {
		flexDirection: "row",
		alignItems: "flex-end",
		gap: 10,
		padding: 12,
		borderTopWidth: 1,
	},
	commentInput: {
		flex: 1,
		borderRadius: 20,
		paddingHorizontal: 14,
		paddingVertical: 10,
		fontSize: 15,
		maxHeight: 100,
	},
	commentSendBtn: { width: 40, height: 40, borderRadius: 20, justifyContent: "center", alignItems: "center" },
});
